url: http://amitkaps.com/stories
baseurl: /stories

permalink: pretty

collections:
  sketches:
    output: true

defaults:
  - scope:
      path: "sketches"
    values:
      layout: "sketch"
# plugins:
#   - jekyll-default-layout
