url: https://amitkaps.com/artistry
baseurl: /artistry

permalink: pretty

collections:
  sketches:
    output: true

defaults:
  - scope:
      path: "sketches"
    values:
      layout: "sketch"
# plugins:
#   - jekyll-default-layout
