url: https://amitkaps.com/artistry
baseurl: /artistry

permalink: pretty
theme: null
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

collections:
  sketches:
    output: true

defaults:
  - scope:
      path: "sketches"
    values:
      layout: "sketch"
